# brownie-config.yaml - Configuration R9 simplifiée

project_structure:
  build: build
  contracts: contracts
  scripts: scripts
  tests: tests

compiler:
  solc:
    version: 0.8.19
    optimizer:
      enabled: true
      runs: 200

networks:
  default: development
  
  development:
    host: http://127.0.0.1:8545
    gas_limit: 6721975
    gas_buffer: 1.1
    gas_price: 20000000000
    
  ganache-local:
    host: http://127.0.0.1:7545
    gas_limit: 6721975
    gas_buffer: 1.1
    gas_price: 20000000000

dotenv: .env